package kmworks.dsltools.adt.adt;

/**
 * Generated by ADTgen
 */

/** An interface for visitors over ADT ASTNodes that do not return a value. */
@SuppressWarnings("unused")
public interface NodeVisitor {

    /* Process an instance of Grammar. */
    void forGrammar(Grammar node);
    void endGrammar(Grammar node);

    /* Process an instance of ADT. */
    void forADT(ADT node);
    void endADT(ADT node);

    /* Process an instance of TypeDef. */
    void forTypeDef(TypeDef node);
    void endTypeDef(TypeDef node);

    /* Process an instance of Parameter. */
    void forParameter(Parameter node);
    void endParameter(Parameter node);
    
    /* Process injected named containers */
    void forAux();
    void endAux();
    
}