EscapeSequence
  <- '\\' [btnfr"'\-\[\\\]]
  / UnicodeEscape

UnicodeEscape <- '\\' 'u' HexQuad 

HexQuad       <- HexDigit HexDigit HexDigit HexDigit 
HexDigit      <- [0-9a-fA-F] 

// ----

StringLiteral <- DQ ( EscapeSequence / !DQ . )* DQ

EscapeSequence <-
        CharEscape
    /   UnicodeEscape

UnicodeEscape <- ESC 'u' HexQuad

CharEscape <- ESC [btnfr"'\-\[\\\]]

HexQuad       <- HexDigit HexDigit HexDigit HexDigit
HexDigit      <- [0-9a-fA-F]

ESC <- '\\'
DQ  <- '\"'
