/*
 *  PEG grammar
 */

Grammar         <-  w Definition+ EOI

Definition      <-  Identifier DEFINES w Expression

Expression      <-  Sequence (ALT Sequence)* ALT?

Sequence        <-  Term+

Term            <-  ( AND / NOT )? Primary ( OPTION / STAR / PLUS / )

Primary         <-  Identifier !DEFINES
                    / LPAREN Expression RPAREN
                    / Terminal

Terminal        <-  StringLiteral w
                    / LBRACK CodePointRange+ RBRACK
                    / DOT

CodePointRange  <- CodePoint '-' CodePoint
                    / CodePoint

CodePoint       <-  EscapeSequence / !ESC .

EscapeSequence  <-  ESC [nrt'"\[\]\\]
                    / UnicodeEscape

UnicodeEscape   <-  ESC 'u' HexQuad
HexQuad         <-  HexDigit HexDigit HexDigit HexDigit
HexDigit        <-  [0-9a-fA-F]

DEFINES     <-  "<-"
ALT         <-  '/' w
AND         <-  '&' w
NOT         <-  '!' w
OPTION      <-  '?' w
STAR        <-  '*' w
PLUS        <-  '+' w
LPAREN      <-  '(' w
RPAREN      <-  ')' w
LBRACK      <-  '[' 
RBRACK      <-  ']' w
DOT			<-	'.' w

ESC			<-  '\\'
EOI         <-  !.