package kmworks.dsltools.ast.${grammar.adt().name()?lower_case};

/*
 * Generated by ADTgen
 */

/** An interface for visitors over ADT ASTNodes that do not return a value. */
@SuppressWarnings("unused")
public interface NodeVisitor {

<#list grammar.adt().main().list() as td>
    <#assign typeName = td.name()>
    /** Process an instance of ${typeName}. */
    public void for${typeName}(${typeName} node);
    public void end${typeName}(${typeName} node);

</#list>
}
